name: backend test

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/backend-test.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run Backend Tests
        working-directory: ./backend
        run: make test
